### PR TITLE
Fixes #8227 - added containers, image and tags

### PR DESCRIPTION
**Pull request by mbacovsky**
- all commands were moved under docker subcommand
- image and tag were moved from hammer-cli-katello

### CODE REVIEW

**Comment by mbacovsky** [comment]
PR to remove moved `image` and `tag` commands from `hammer-cli-katello`: https://github.com/Katello/hammer-cli-katello/pull/276

**Comment by mbacovsky** [comment]
PR to remove moved `image` and `tag` commands from `hammer-cli-katello`: https://github.com/Katello/hammer-cli-katello/pull/276

**Comment by mbacovsky** [comment]
PR to remove moved `image` and `tag` commands from `hammer-cli-katello`: https://github.com/Katello/hammer-cli-katello/pull/276

**Comment by mbacovsky** [comment]
`docker container log` command wont work without https://github.com/theforeman/hammer-cli-foreman/pull/170 merged in `hammer-cli-foreman`

**Comment by daviddavis** [comment]
The CLI commands tag and image work great. I tried the container command but it looks like the apidoc is messed up. It's showing `/api/v2/containers` when it should say `/docker/api/v2/containers` so I am getting:

```
$ hammer docker container list
404 Resource Not Found
```

This is not an issue with this PR but I can't test it out. Pinged @eLobato about it.

**Comment by daviddavis** [comment]
When I tested with https://github.com/theforeman/foreman-docker/pull/89, it works great. I did notice you didn't have container create yet. I assume that is coming next (in a separate PR).

:+1:

**Comment by daviddavis** [comment]
One small bug I found:

```
❯❯❯ h docker container list
---|---------------|------------------|--------|---------|-----------------
ID | NAME          | IMAGE REPOSITORY | TAG    | COMMAND | COMPUTE RESOURCE
---|---------------|------------------|--------|---------|-----------------
1  | test          | centos           | latest | bash    | MyDocker
2  | fdsfjkdsldsfj | centos           | latest | bash    | MyDocker
---|---------------|------------------|--------|---------|-----------------
❯❯❯ h docker container info --name test
Error: container found more than once
❯❯❯ h docker container info --name test --compute-resource MyDocker
Error: container found more than once
```

**Comment by mbacovsky** [comment]
Create command added. Plus some configuration instructions

**Comment by daviddavis** [comment]
I found some problems in the Container API but your CLI stuff here works well. ACK

:+1:

**Comment by daviddavis** [comment]
Opened https://github.com/theforeman/foreman-docker/pull/92 to address the API problems I found.

**Pull request merged**
